name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    name: Greet First-Time Contributors
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    if: ${{ github.actor != 'dependabot[bot]' && github.actor != 'github-actions[bot]' }}
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            👋 Hi @${{ github.actor }}!

            Thanks for opening your first issue here 🎉  
            We appreciate your contribution and will review it as soon as possible.
          pr-message: |
            🎉 Hi @${{ github.actor }}!

            Thanks for submitting your first Pull Request!  
            We’re thrilled to have your contribution and will review it shortly.